### ISSUE TITLE
代码疑问咨询

### ISSUE THREAD

**Issue by huangdengdeng-098** [Euclid-Jie/Euclidweibo-search#1]
![图片](https://user-images.githubusercontent.com/78304054/200452864-d9a92962-996c-4b23-9d5b-b794d600107c.png)
您好！您的微博爬取数据代码给我很大的帮助，十分感谢！！但是我在运行过程中遇到了这个问题，尝试解决未果，所以冒昧打扰您，不知道是否可以麻烦您解答一下！设置日期在2021或者之前的时候，他似乎会自动更新时间跨度到2022年，无法获取指定时间内的内容~（没有改过源代码，只更新了自己的cookie）

**Comment by Euclid-Jie** [comment]
可尝试修改最后一个参数为40

**Comment by Euclid-Jie** [comment]
相关问题已修复，请查看最新代码

**Comment by huangdengdeng-098** [comment]
好的，谢谢您！我会再试试的！非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月8日(周二) 下午3:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Euclid-Jie/Euclidweibo-search] 代码疑问咨询 (Issue #1)




 
相关问题已修复，请查看最新代码
