### ISSUE TITLE
没有爬取规定时间范围内的相关微博

### ISSUE THREAD

**Issue by woshilmz** [Euclid-Jie/Euclidweibo-search#10]
您好，想要爬取2023.2.1-2023.5.1时间段内“AI”为关键词的微博时，运行并未报错，但运行结果文件中只包含了2023.4.30的相关微博。
if __name__ == '__main__':
    timeBegin = '2023-02-01-0'
    timeEnd = '2023-05-01-0'
    demoClass = WeiboClassV1(Mongo=False, contains=False)
    demoClass.main_get(['AI'], timeBegin, timeEnd)

同样，在爬取2023.2.1-2023.7.10时间段内”人工智能“为关键词的微博时，运行结果的excel文件只出现了2023.9.19、7.14、7.6这三天的相关微博。不知道是什么原因造成的？
if __name__ == '__main__':
    timeBegin = '2023-02-01-0'
    timeEnd = '2023-07-10-0'
    demoClass = WeiboClassV1(Mongo=False, contains=False)
    demoClass.main_get(['人工智能'], timeBegin, timeEnd)

另外想问一下如果想爬取 同时出现”人工智能“&”大数据“这两个关键词 的相关微博，该如何设置？
如能回复万分感谢

**Comment by Euclid-Jie** [comment]
@woshilmz 设置cookie了吗，同时我更建议你尝试使用[WeiboClassRun](https://github.com/Euclid-Jie/Euclidweibo-search/blob/3373d9268d9335021e710bcba8f0d5569bcfc02e/WeiboClassRun.py#L54)
> 另外想问一下如果想爬取 同时出现”人工智能“&”大数据“这两个关键词 的相关微博，该如何设置？ 如能回复万分感谢

我理解是这只key为`人工智能 大数据`就可以了，中间是空格；所获取的数据是比较模糊的，对于爬取下来的结果可以再进行严格的筛选（也就是你说的同时包含这两个）

---
如果有问题欢迎继续comments

**Comment by Euclid-Jie** [comment]
> 同样，在爬取2023.2.1-2023.7.10时间段内”人工智能“为关键词的微博时，运行结果的excel文件只出现了2023.9.19、7.14、7.6这三天的相关微博。不知道是什么原因造成的？

我用你的参数，实验了一下，这是输出
>get 人工智能 blog data begin ... 
> time span: 2023-02-01-0 - 2023-07-10-0
>100%|██████████| 50/50 [00:30<00:00,  1.65it/s, 状态=已写num:4]
> time span: 2023-02-01-0 - 2023-07-09-18
>100%|██████████| 50/50 [00:29<00:00,  1.69it/s, 状态=已写num:10]
> time span: 2023-02-01-0 - 2023-07-09-12
>100%|██████████| 50/50 [00:32<00:00,  1.54it/s, 状态=已写num:7]
> time span: 2023-02-01-0 - 2023-07-09-00
....

说明是可以爬取指定该时间跨度的数据的

**Comment by Euclid-Jie** [comment]
如果有需要我可以爬完给你，我的QQ是`2379928684`

**Comment by Euclid-Jie** [comment]
'''python
print("hello word")
'''

**Comment by woshilmz** [comment]
非常感谢回复
更新了cookie,使用WeiboClassRun得到了想要的结果。
之前可能是将缓存文件当成结果文件了T T
祝好！
