### ISSUE TITLE
您好，我在运行程序的时候发现在爬评论的时候2020年的部分评论无法爬取，试了几个关键词（例如九寨沟、澳门等）都不行，会报错“No columns to parse from file”，麻烦您有时间的时候可以看一下，万分感谢！

### ISSUE THREAD

**Issue by ReckyBuckley** [Euclid-Jie/Euclidweibo-search#3]

**Comment by Euclid-Jie** [comment]
更新了cookie吗，如果更新了可以截图看一下您的参数和报错内容，因为我这边试了一下您说的参数，没有报错
***@***.***
发件人: ***@***.***>
发送时间: 2023年2月4日 18:04
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Euclid-Jie/Euclidweibo-search] 您好，我在运行程序的时候发现在爬评论的时候2020年的部分评论无法爬取，试了几个关键词（例如九寨沟、澳门等）都不行，会报错“No columns to parse from file”，麻烦您有时间的时候可以看一下，万分感谢！ (Issue #3)


―

**Comment by Euclid-Jie** [comment]
或者有可能您误用了数据库写入类，可以在runclass中修改一下

**Comment by Euclid-Jie** [comment]
> 

我已更新runclass文件中两张写入方式的说明，您可以重新拉一下（下载文件），如果仍有问题请继续留言

**Comment by ReckyBuckley** [comment]
您好，我的参数和报错如下，敦煌作关键词时




四姑娘山做关键词时，因为四姑娘山我之前爬取了2020-11-15到2022年8月的数据，所以表里面有一部分数据，然后20年剩下的数据就一点都没有抓取了：







在 2023-02-04 20:30:19，"欧玮杰" ***@***.***> 写道：

或者有可能您误用了数据库写入类，可以在runclass中修改一下

**Comment by Euclid-Jie** [comment]
> 

可以加我qq：2379928684，我好像看不到您的图片

**Comment by ReckyBuckley** [comment]
您好，我刚才下载了您最新更新的代码，现在可以运行了，可以成功爬取了，真的非常感谢！



在 2023-02-04 20:48:49，"欧玮杰" ***@***.***> 写道：

可以加我qq：2379928684，我好像看不到您的图片
