### ISSUE TITLE
请问cookie是哪个名字cookie

### ISSUE THREAD

**Issue by banduoba** [Euclid-Jie/Euclidweibo-search#4]
header中的cookie需要登录微博网页版后获取，登录网址为：https://s.weibo.com/

**Comment by Euclid-Jie** [comment]
这句话是指，需要登录您个人的微博后，获取cookie，存放到cookie.txt中，您可以进一步解释遇到的问题，这样我可以为您提供更精确的解决方式

**Comment by Euclid-Jie** [comment]
> header中的cookie需要登录微博网页版后获取，登录网址为：https://s.weibo.com/

这句话是指，需要登录您个人的微博后，获取cookie，存放到cookie.txt中，您可以进一步解释遇到的问题，这样我可以为您提供更精确的解决方式

**Comment by banduoba** [comment]
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/4811366/227788946-e9776dba-0553-4d4b-a475-449e995d7bd8.png">
应该获取哪个cookie的名字

**Comment by banduoba** [comment]
我明白了

**Comment by banduoba** [comment]
长期维护么大佬 抖音的采集有做么

**Comment by Euclid-Jie** [comment]
没做抖音，微博这我一会传一个2.0版本上来

**Comment by banduoba** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/4811366/227932341-0ada339c-8f5a-4953-9989-8c0736999603.png">
2.0版本和之前的版本采集的数据都是空了好像

**Comment by Euclid-Jie** [comment]
> <img alt="image" width="652" src="https://user-images.githubusercontent.com/4811366/227932341-0ada339c-8f5a-4953-9989-8c0736999603.png">
> 
> 2.0版本和之前的版本采集的数据都是空了好像

我debug一下

**Comment by Euclid-Jie** [comment]
已修复，你重新拉一下

**Comment by Euclid-Jie** [comment]
> 已修复，你重新拉一下

用WeiboClassV2.py这个

**Comment by banduoba** [comment]
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/4811366/227990479-53fd368c-4920-4d18-a99c-952fc92d2959.png">

WeiboClassV2.py 也不行

**Comment by Euclid-Jie** [comment]
> <img alt="image" width="1350" src="https://user-images.githubusercontent.com/4811366/227990479-53fd368c-4920-4d18-a99c-952fc92d2959.png">
> 
> WeiboClassV2.py 也不行

不会啊，没更新cookie吧

**Comment by banduoba** [comment]
是的 确实cookie问题 现在好了 大佬

**Comment by banduoba** [comment]
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
采集没有完毕就出现这个报错什么情况,昨天升级之前好像都好好的

**Comment by Euclid-Jie** [comment]
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 采集没有完毕就出现这个报错什么情况,昨天升级之前好像都好好的

我处理一下

**Comment by Euclid-Jie** [comment]
修复了
