### ISSUE TITLE
如何获取对应微博内容的图片链接或者视频链接一起保存到表格呢

### ISSUE THREAD

**Issue by banduoba** [Euclid-Jie/Euclidweibo-search#5]

**Comment by Euclid-Jie** [comment]
> 

需要改写函数：select_field，加入你想要的字段

**Comment by banduoba** [comment]
WeiboClassV2('唐山打人', Mongo=False).main('2022-06-01-00', '2023-03-27-21')
V2和V3运行后都提示这个
requests.exceptions.SSLError: HTTPSConnectionPool(host='s.weibo.com', port=443): Max retries exceeded with url: /weibo?q=%E5%94%90%E5%B1%B1%E6%89%93%E4%BA%BA&typeall=1&suball=1&timescope=custom%3A2022-06-01-00%3A2023-03-27-21&Refer=g&page=11 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

网络问题，检查是否用了代理

**Comment by banduoba** [comment]
```
 def select_field(data):
        selectedData = {
            'time': data['created_at'],
            'mid': data['mid'],
            'nick_name': data['user']['screen_name'],
            'attitudes_count': data['attitudes_count'],
            'comments_count': data['comments_count'],
            'reposts_count': data['reposts_count'],
            'text': data['text'],
            'text_raw': data['text_raw'],
            'longTextContent': data['longTextContent']
        }
        ```
 我应该增加什么字段呢 如果想要图片或者视频的URL保存在表格

**Comment by Euclid-Jie** [comment]
> ```
>  def select_field(data):
>         selectedData = {
>             'time': data['created_at'],
>             'mid': data['mid'],
>             'nick_name': data['user']['screen_name'],
>             'attitudes_count': data['attitudes_count'],
>             'comments_count': data['comments_count'],
>             'reposts_count': data['reposts_count'],
>             'text': data['text'],
>             'text_raw': data['text_raw'],
>             'longTextContent': data['longTextContent']
>         }
>         ```
>  我应该增加什么字段呢 如果想要图片或者视频的URL保存在表格
> ```

这个要根据你的实际需求，比如是需要视频链接，加入这个['page_info']['media_info']['mp4_720p_mp4']，依据为下图
![image](https://user-images.githubusercontent.com/71357995/228742534-7f48e014-8a57-4dff-91a6-257650f32ac8.png)

**Comment by Euclid-Jie** [comment]
具体操作方式可以[参照](https://blog.csdn.net/wr1037/article/details/108599300)，需要查看的是以myblog开头的请求，并预览其返回值，数据结构就是dict
![image](https://user-images.githubusercontent.com/71357995/228743170-659f5922-2b34-4cfc-9372-abf0b3557f43.png)

**Comment by banduoba** [comment]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/4811366/228775040-30067eb7-b202-4fc8-8322-31775efb6679.png">
F12ud刷新就debug 大佬这个怎么解决呢

**Comment by banduoba** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/4811366/228797100-2950184c-2207-4bfa-aff0-ea4f18c3912b.png">
'video_url': data['page_info']['media_info']['mp4_720p_mp4'],
            'img_url': data['pic_infos']['original']['url']
加上上面的之后运行就提示出错了

**Comment by Euclid-Jie** [comment]
我在上课，稍晚点看代码

**Comment by banduoba** [comment]
好的大佬,希望可以更新下支持保存图片和视频链接到表格

**Comment by banduoba** [comment]
可以增加下的么

**Comment by Euclid-Jie** [comment]
更新了视频链接video_url，你报错的原因是因为有些微博没有视频，缺少字段。
图片链接有访问限制，无法处理。你可以通过微博地址mblogUrl查看具体内容（包括视频和图片）。

**Comment by banduoba** [comment]
返回的字段里面不是有图片地址么,我只需保存图片地址不需要访问,可以加的么

**Comment by banduoba** [comment]
我刚刚自己加入了图片获取保存,已经OK了,这个图片直接访问确实有问题,获取到图片链接直接复制到浏览器可以打开,直接点击打不开

**Comment by Euclid-Jie** [comment]
> 我刚刚自己加入了图片获取保存,已经OK了,这个图片直接访问确实有问题,获取到图片链接直接复制到浏览器可以打开,直接点击打不开

确实，直接点不开，所以我没加

**Comment by Euclid-Jie** [comment]
不过你可能需要考虑，一个微博可能有多个图片

**Comment by banduoba** [comment]
没事 我只需要有一个图片就行了,就是一个舆情根据视频和图片分类的作业分析 图片能不能访问不重要 谢谢大佬的这个 页面放一个打赏感谢的二维码呗

**Comment by Euclid-Jie** [comment]
> 没事 我只需要有一个图片就行了,就是一个舆情根据视频和图片分类的作业分析 图片能不能访问不重要 谢谢大佬的这个 页面放一个打赏感谢的二维码呗

不需要，感谢你对我的项目提出的一系列建议，可以加我qq:2379928684，后续可以继续沟通
