### ISSUE TITLE
AttributeError: 请更新Cookie, 并等候片刻后重试!, 当前状态码为:414

### ISSUE THREAD

**Issue by banduoba** [Euclid-Jie/Euclidweibo-search#6]
raise AttributeError("请更新Cookie, 并等候片刻后重试!, 当前状态码为:{}".format(response.status_code))
AttributeError: 请更新Cookie, 并等候片刻后重试!, 当前状态码为:414

换了好几个cookie 都提示上面的内容

**Comment by Euclid-Jie** [comment]
>     raise AttributeError("请更新Cookie, 并等候片刻后重试!, 当前状态码为:{}".format(response.status_code))
> AttributeError: 请更新Cookie, 并等候片刻后重试!, 当前状态码为:414
> 
> 换了好几个cookie 都提示上面的内容

先使用v2，稍晚我看一下原因

**Comment by Euclid-Jie** [comment]
这个和电脑的配置、及网速有一定的关系，可以尝试改小`max_work_count`参数，默认为20
`WeiboClassV3('央视频', Mongo=False, max_work_count=10).main('2023-02-11-00', '2023-03-27-21')`

**Comment by Euclid-Jie** [comment]
进一步的通用解决方式后续将开发，目前您可以使用V2或者更改参数的方式

> 这个和电脑的配置、及网速有一定的关系，可以尝试改小`max_work_count`参数，默认为20 `WeiboClassV3('央视频', Mongo=False, max_work_count=10).main('2023-02-11-00', '2023-03-27-21')`

**Comment by banduoba** [comment]
好的 配置应该不低的 iMac 64G内存 10代i7处理器 网速也是超级快的

**Comment by Euclid-Jie** [comment]
> 好的 配置应该不低的 iMac 64G内存 10代i7处理器 网速也是超级快的

好，确实配置杠杠的，羡慕了。可能真的受到到了微博反爬，那其实还挺难办的，可以加我QQ交流2379928684

**Comment by Euclid-Jie** [comment]
最新发现是由于请求过多，封禁了IP。我再想办法

**Comment by banduoba** [comment]
> > 好的 配置应该不低的 iMac 64G内存 10代i7处理器 网速也是超级快的
> 
> 好，确实配置杠杠的，羡慕了。可能真的受到到了微博反爬，那其实还挺难办的，可以加我QQ交流2379928684

哈哈 闲鱼上买的二手的
 我说呢 或者 可以增加一个代理ip池么 或者怎么接入第三方的

**Comment by Euclid-Jie** [comment]
推送了IP代理设置，如果你有梯子的话可以在set_proxies中设置端口。如果实在是不行，先用V1吧。后面我想一下怎么弄

**Comment by Euclid-Jie** [comment]
> > > 好的 配置应该不低的 iMac 64G内存 10代i7处理器 网速也是超级快的
> > 
> > 
> > 好，确实配置杠杠的，羡慕了。可能真的受到到了微博反爬，那其实还挺难办的，可以加我QQ交流2379928684
> 
> 哈哈 闲鱼上买的二手的 我说呢 或者 可以增加一个代理ip池么 或者怎么接入第三方的

可以接第三方，也可以是自己的梯子
`IP = '{}:{}'.format(http, port)`

**Comment by Euclid-Jie** [comment]
V1版本上线，与V2，V3请求逻辑不同，不会被封号
