### ISSUE TITLE
format_time方法报错IndexError: list index out of range

### ISSUE THREAD

**Issue by Popantelope** [Euclid-Jie/Euclidweibo-search#8]
您好！
在’# 距离数据采集时间一小时内, 使用当前时间回望‘这个elif内报错
![image](https://github.com/Euclid-Jie/Euclidweibo-search/assets/76279091/a7c8b465-647a-46e2-b0f0-5c34df000c63)
使用的是V1版本代码
![image](https://github.com/Euclid-Jie/Euclidweibo-search/assets/76279091/a46c5480-b5c9-4446-8995-3f19f2a0c8dd)
请问这是由于什么原因呢？是因为正则匹配出错了导致未匹配到数据吗？或许是因为网页发生了改动？由于不太了解您写代码的分析过程，所以不知道具体是因为什么原因，望您能够抽空解答，谢谢！

**Comment by Popantelope** [comment]
对了，只是部分情况下会出现这种错误，并不是所有情况下都会报错

**Comment by Euclid-Jie** [comment]
> 对了，只是部分情况下会出现这种错误，并不是所有情况下都会报错

把你的参数发我，我debug一下

**Comment by Popantelope** [comment]
> 

我是以“疫情”为关键词，时间范围是从2020-07-01-00到2020-07-10-21的范围运行时出现的这个错误，我发现这个错误有时会出现，有时又不会，不知道是代码的问题还是我本身网络的问题，比如网速慢导致页面元素还未加载完

**Comment by Euclid-Jie** [comment]
> > 
> 
> 我是以“疫情”为关键词，时间范围是从2020-07-01-00到2020-07-10-21的范围运行时出现的这个错误，我发现这个错误有时会出现，有时又不会，不知道是代码的问题还是我本身网络的问题，比如网速慢导致页面元素还未加载完

关于正则无法匹配到一小时内的时间，已解决
