### ISSUE TITLE
一直在重复爬同一个微博怎么解决

### ISSUE THREAD

**Issue by Wang-Yuhao0315** [Euclid-Jie/Euclidweibo-search#9]
<img width="960" alt="dfd01d1e055e2c831964050793d4150" src="https://github.com/Euclid-Jie/Euclidweibo-search/assets/112491890/b9a2770e-9d03-4e2c-a482-362ef628ef91">

**Comment by Euclid-Jie** [comment]
具体看一下你的参数，我需要复现你的报错后，查找原因并修复

**Comment by Wang-Yuhao0315** [comment]
您好！参数如下，其余部分我并未改动
__name__ == '__main__':
    timeBegin = '2018-05-19-0'
    timeEnd = '2023-05-19-0'
    demoClass = WeiboClassV1(Mongo=False)
    demoClass.main_get(['生态消费'], timeBegin, timeEnd)
非常感谢的您的回复！

**Comment by Euclid-Jie** [comment]
> 您好！参数如下，其余部分我并未改动 **name** == '**main**': timeBegin = '2018-05-19-0' timeEnd = '2023-05-19-0' demoClass = WeiboClassV1(Mongo=False) demoClass.main_get(['生态消费'], timeBegin, timeEnd) 非常感谢的您的回复！

已修复，即将推送最新版本，请注意，contains参数。
因为您的“生态消费”很少在微博正文中出现，所以大量微博被筛选剔除，可以通过设置contains=False，以关闭筛选。

**Comment by Euclid-Jie** [comment]
记得给我stars一下，有问题可以继续开issue问
